title: Jamie's personal blog
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  My name is Jamie Davidson, and I'm a software engineer
  from Cambridge, England. This website was created in effort to do
  more technical writing, and encourage me to talk about my side projects.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jamiedavidson.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  jamiedavidson
github:
  owner_url: https://github.com/jamiedavidson
  owner_name: jamiedavidson

# Build settings
markdown: kramdown
theme: jekyll-theme-midnight
plugins:
  - jekyll-feed
  
future: true

assets:
  digest: true
  compress:
    css:  true
    js:   uglifier
  prefix: "/assets"
  sources:
    - assets/*

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
